source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

xcodeproj 'RecastAI.xcodeproj'

target 'RecastAI_Example', :exclusive => true do
  pod 'RecastAI', :path => '../'
  pod 'JSONJoy-Swift'
  pod 'Alamofire'
end

target 'RecastAI_Tests', :exclusive => true do
  pod 'RecastAI', :path => '../'
  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
end
