source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

xcodeproj 'RecastAI.xcodeproj'

target 'RecastAI_Tests', :exclusive => true do
  pod 'RecastAI', :path => '../'
  pod 'SwiftHTTP'
  pod 'JSONJoy-Swift'
end
